name = "RationalPolygons"
uuid = "d26dedfb-ad13-44bd-90c7-a2710fa2c005"
authors = ["Justus Springer <justusspringer@gmx.de>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
