name = "RationalPolygons"
uuid = "d26dedfb-ad13-44bd-90c7-a2710fa2c005"
authors = ["Justus Springer <justusspringer@gmx.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
